version:     '{build}'
clone_depth: 1
environment:
    matrix:
        - VIM_URL: http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip
install:
    - 'cd %APPVEYOR_BUILD_FOLDER%'
    - 'appveyor DownloadFile %VIM_URL% -FileName %TEMP%\vim.zip'
    - '7z x -o%TEMP% %TEMP%\vim.zip > nul'
    - ps: $Env:THEMIS_VIM = (Get-ChildItem $Env:TEMP | Select-Object -First 1).FullName + '\vim.exe'
    - 'git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --quiet --branch v1.5 --single-branch --depth 1 %TEMP%\vim-themis'
build: off
test_script:
    - '%THEMIS_VIM% --version'
    - '%TEMP%\vim-themis\bin\themis.bat tests/ -r --reporter dot'
deploy: off
